"""added 2fa for claim

Revision ID: 3d29b2f1996d
Revises: 23b55a52f1d8
Create Date: 2026-02-11 04:14:42.324740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d29b2f1996d'
down_revision: Union[str, Sequence[str], None] = '23b55a52f1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('founder_confirmed', sa.Boolean(), nullable=True))
    op.add_column('claims', sa.Column('loser_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claims', 'loser_confirmed')
    op.drop_column('claims', 'founder_confirmed')
    # ### end Alembic commands ###
